package(default_visibility = ["//visibility:public"])

#filegroup(
#    name = "srcs",
#    srcs = glob(["**"]) + [
#        "//src/main/java/com/example/myproject:srcs",
#        "//src/main/resources:srcs",
#        "//src/test/java/com/example/myproject:srcs",
#    ],
#)
